INSERT INTO PERSON (ID, NAME) VALUES (1, 'Per');
INSERT INTO PERSON (ID, NAME) VALUES (2, 'Kari');
INSERT INTO PERSON (ID, NAME) VALUES (3, 'Marianne');
INSERT INTO PERSON (ID, NAME) VALUES (4, 'Ola');